/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import cards.Card;
import java.util.HashMap;
import javax.swing.JLabel;
import players.User;

/**
 *
 * @author Владимир
 */
public class GameWindow extends javax.swing.JFrame {

    private User user;
    private Card myCard;
    private HashMap<String, Card> otherCards;
    
    public GameWindow(User user) {
        initComponents();
        this.user = user;
    }

    public void setMyCard(Card myCard) {
        this.myCard = myCard;
    }

    public void setOtherCards(HashMap<String, Card> otherCards) {
        this.otherCards = otherCards;
    }

    public JLabel getLastCardLabel() {
        return lastCardLabel;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        viewOtherCardsButton = new javax.swing.JButton();
        viewMyCardButton = new javax.swing.JButton();
        takeCardButton = new javax.swing.JButton();
        refuseButton = new javax.swing.JButton();
        lastCardLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Карта"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        viewOtherCardsButton.setBackground(new java.awt.Color(252, 252, 252));
        viewOtherCardsButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        viewOtherCardsButton.setText("Посмотреть чужую карту");

        viewMyCardButton.setBackground(new java.awt.Color(252, 252, 252));
        viewMyCardButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        viewMyCardButton.setText("Посмотреть свою карту");
        viewMyCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMyCardButtonActionPerformed(evt);
            }
        });

        takeCardButton.setBackground(new java.awt.Color(252, 252, 252));
        takeCardButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        takeCardButton.setText("Взять карту");

        refuseButton.setBackground(new java.awt.Color(252, 252, 252));
        refuseButton.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        refuseButton.setText("Отказаться");

        lastCardLabel.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        lastCardLabel.setText("Вы взяли карту - ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewMyCardButton)
                    .addComponent(viewOtherCardsButton)
                    .addComponent(takeCardButton)
                    .addComponent(refuseButton)
                    .addComponent(lastCardLabel))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lastCardLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewOtherCardsButton)
                .addGap(18, 18, 18)
                .addComponent(viewMyCardButton)
                .addGap(18, 18, 18)
                .addComponent(takeCardButton)
                .addGap(18, 18, 18)
                .addComponent(refuseButton)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewMyCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMyCardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewMyCardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastCardLabel;
    private javax.swing.JButton refuseButton;
    private javax.swing.JButton takeCardButton;
    private javax.swing.JButton viewMyCardButton;
    private javax.swing.JButton viewOtherCardsButton;
    // End of variables declaration//GEN-END:variables
}
